
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
    - sudo apt-get install libgsl0-dev
    - Rscript -e 'install.packages("RcppEigen", dependencies = TRUE)'
    - Rscript -e 'install.packages("RcppGSL", dependencies = TRUE)'
    - Rscript -e 'install.packages("mvabund", dependencies = TRUE)'
    - Rscript -e 'install.packages("TMB", dependencies = TRUE)'
    - Rscript -e 'install.packages("matrixStats", dependencies = TRUE)'
    - Rscript -e 'install.packages("mvtnorm", dependencies = TRUE)'
