all: genDA_f.so genDA_f_null_X.so genDA_f_predict_approximation.so
	# Comment here preserves the prior tab
genDA_f.so: genDA_f.cpp
	Rscript --vanilla -e "TMB::compile('genDA_f.cpp','-O0 -g')"
genDA_f_null_X.so: genDA_f_null_X.cpp
	Rscript --vanilla -e "TMB::compile('genDA_f_null_X.cpp','-O0 -g')"
genDA_f_predict_approximation.so: genDA_f_predict_approximation.cpp
	Rscript --vanilla -e "TMB::compile('genDA_f_predict_approximation.cpp','-O0 -g')"

clean:
	rm -rf *o